### ISSUE TITLE
Write simple engine that prioritizes minor piece development

### ISSUE THREAD

**Issue by sansona** [sansona/chessmate#15]
The equivalent of `PrioritizePawnMoves` but for minor pieces

**Comment by Grace-Hamilton** [comment]
Hi @sansona do you need assistance with this? If so, would you mind if I help you?

**Comment by Grace-Hamilton** [comment]
Thanks @sansona! Just to clarify, do you want minor pieces to move randomly like the pawns do in PrioritizePawnMoves or is there supposed to be an extra algorithm to their movement?

**Comment by sansona** [comment]
Up to you! With the basic engines I'm mostly interested in them being there for demonstration purposes i.e "Here's what an engine that obeys this simple heuristic does." I envision at some point I'd like to incorporate functionality such that engines can be combined so if I am to weigh in I'd say the simpler the better for the time being, but I absolutely wouldn't be opposed if you wanted to make it more functional
